#!/bin/sh
vcs -full64 ../par/efficient_mac.v ../rtl/stim.v +v2k -sdf max:stim/uut:../par/efficient_mac.sdf -debug_all -top stim -timescale=1ns/1ps +neg_tchk +warn=noTFIPC -v /dfs/app/tsmc_icdc/tsmc180/tsmc180_MS_RF_G/SC/tcb018g3d3/Rev280a/Front_End/verilog/tcb018g3d3_280a/tcb018g3d3.v
./simv -ucli
